name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          openjdk-17-jdk \
          unzip \
          zip \
          git \
          wget \
          zlib1g-dev \
          yes \
          python3-pip

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython buildozer

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
        unzip -q tools.zip
        mv cmdline-tools latest
        rm tools.zip

    - name: Install Android SDK packages
      env:
        ANDROID_SDK_ROOT: $HOME/android-sdk
        PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$PATH
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: $HOME/android-sdk
        PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: teacher-selector-apk
        path: bin/*.apk
