name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          tar \
          libtool \
          autoconf \
          automake \
          pkg-config

    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython

    - name: Create buildozer.spec if missing
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.android && echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg

    - name: Build the APK
      run: |
        buildozer android debug
