name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Pin to Ubuntu 22.04 to avoid breaking packages on 24.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libtool \
          autoconf \
          automake \
          pkg-config \
          libncurses5-dev \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libjpeg-dev \
          libfreetype6-dev \
          libpng-dev \
          libc6-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          x11proto-core-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxi-dev

    - name: Upgrade pip and install Buildozer & dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip install cython buildozer

    - name: Create buildozer.spec if missing
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.android && echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg

    - name: Build the APK
      run: |
        buildozer android debug
