name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROIDSDK: ${{ github.workspace }}/android-sdk
      ANDROIDNDK: ${{ github.workspace }}/android-ndk-r25b
      ANDROIDAPI: 33
      ANDROIDMINAPI: 21

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      - name: Download and setup Android SDK
        run: |
          mkdir -p $ANDROIDSDK
          cd $ANDROIDSDK
          # Download command for SDK tools, e.g.:
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools $ANDROIDSDK/cmdline-tools/latest
          yes | $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;27.2.1240187"

      - name: Download and setup Android NDK
        run: |
          mkdir -p $ANDROIDNDK
          cd $ANDROIDNDK
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b/* .
          rm -rf android-ndk-r25b

      - name: Install Apache Ant manually
        run: |
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
          tar -xzf apache-ant-1.9.4-bin.tar.gz
          mv apache-ant-1.9.4 $HOME/apache-ant
          echo "$HOME/apache-ant/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          buildozer android debug
