name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          python3-pip \
          openjdk-17-jdk \
          unzip \
          zip \
          git \
          zlib1g-dev \
          wget

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Set up Android SDK
      run: |
        mkdir -p android-sdk/cmdline-tools
        cd android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip

    - name: Install Android SDK packages
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/emulator:$PATH
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:$PATH
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: teacherselector-apk
        path: bin/*.apk
