name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.workspace }}/android-sdk
      PATH: ${{ runner.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ runner.workspace }}/android-sdk/platform-tools:${{ env.PATH }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          python3-pip \
          openjdk-17-jdk \
          unzip \
          zip \
          git \
          libstdc++6 \
          zlib1g \
          zlib1g-dev \
          wget

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Setup Android SDK Command Line Tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        rm cmdline-tools.zip
        mv cmdline-tools latest

    - name: Accept licenses and install SDK packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: teacherselector-apk
        path: bin/*.apk
