[app]

# (str) Title of your application
title = Teacher Selector

# (str) Package name
package.name = teacherselector

# (str) Package domain (reverse DNS style)
package.domain = org.example

# (str) Source code where your main.py is located
source.dir = .

# (str) Application version
version = 1.0.0

# (list) Application requirements
requirements = python3,kivy

# (str) Entry point of your app
# (use the filename of your main python script)
entrypoint = main.py

# (str) Supported orientation (portrait, landscape or all)
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (list) Permissions to request
android.permissions = INTERNET

# (int) Android API to target (must be installed in SDK)
android.api = 33

# (int) Minimum Android API your app supports
android.minapi = 21

# (int) Android SDK build tools version (should match what is installed)
android.build_tools_version = 33.0.2

# (str) Android NDK version to use (you can leave blank for default)
# android.ndk = 25b

# (bool) Copy libraries instead of making a .so symlink
android.copy_libs = 1

# (bool) Whether to use --private data storage (better for your app's data)
android.private_storage = True

# (str) Presplash image (optional)
# presplash.filename = %(source.dir)s/data/presplash.png

# (list) Extra source files to include (if any)
# source.include_exts = py,png,jpg,kv,atlas

# (bool) Use a debug build (True for debugging)
# android.debug = True

